services:
  app:
    image: ghcr.io/piecethelord/naskatest-app:latest
    container_name: naskatest-app-api
    restart: always
    healthcheck:
      disable: true # * Remove healthcheck for test
    volumes:
      - /etc/letsencrypt/live/alexey-web-dev.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/alexey-web-dev.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - web
    labels:
      # Enable Traefik and point out the Docker network
      - "traefik.enable=true"
      # 1. Point out the domen
      - "traefik.http.routers.naska-api.rule=Host(`naska-api.alexey-web-dev.ru`)"
      # 2. Get the Traffic by http
      # - "traefik.http.routers.naska-api.entrypoints=web"
      - "traefik.http.routers.naska-api.entrypoints=web,websecure" # Изменили web на websecure
      - "traefik.http.routers.naska-api.tls.certresolver=myresolver" # Сказали выпустить SSL!
      # 3. Point out to Traefik the port of our app
      - "traefik.http.services.naska-api.loadbalancer.server.port=80"

networks:
  web:
    external: true