---
- name: Deploy Simple App
  hosts: webservers
  become: yes # Выполнять задачи с правами sudo

  # Бонус: Использование переменных в playbook
  vars:
    app_port: 5000
    docker_image: simple-app:latest
    app_dir: /opt/simple-app
    docker_compose_version: "v2.24.6"

  roles:
    - role: docker
    - role: app