name: CI/CD Pipeline


on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write


jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install ruff pytest httpx fastapi uvicorn pydantic
          pip install -r app/requirements.txt

      - name: Run Linting (Ruff)
        run: ruff check app/

      - name: Run Tests (Pytest)
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest app/tests/ -v

  build-and-push:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/naskatest-app:latest
            ghcr.io/${{ env.OWNER_LC }}/naskatest-app:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Copy docker-compose via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yaml"
          target: "/opt/naskatest-app"


      - name:  Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/naskatest-app

            echo ${{ secrets.GITHUB_TOKEN }} | docker loginghcr.io -u ${{ github.actor }} --password-stdin

            docker compose pull

            # test
            docker compose up -d

            # Clear old iamges test
            docker image prune -f
